AllCops:
  Exclude:
    - 'vendor/**/*'

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - '**/Berksfile'
    - '**/metadata.rb'

Style/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Berksfile'

Style/RegexpLiteral:
  Exclude:
    - '**/Guardfile'

Style/EmptyLines:
  Exclude:
    - '**/Guardfile'
    - '**/Rakefile'

Style/TrailingBlankLines:
  Exclude:
    - '**/Guardfile'
    - '**/Rakefile'

Metrics/LineLength:
  Exclude:
    - '**/Gemfile'

Metrics/LineLength:
  Max: 156

Metrics/AbcSize:
  Max: 65

Metrics/MethodLength:
  Max: 31

Style/ClosingParenthesisIndentation:
  Enabled: false
