name             'ohai_software'
maintainer       'Nordstrom, Inc.'
maintainer_email 'CHANGE_ME_TO_SOMETHING_APPROPRIATE@nordstrom.com'
license          'All rights reserved'
description      'Installs/Configures ohai_software'
long_description 'Longer version of description: Installs/Configures ohai_software'
version          '0.0.0'
