name             'ohai_software'
maintainer       'Nordstrom, Inc.'
maintainer_email 'itunixadminall@nordstrom.com'
license          'All rights reserved'
description      'Installs the ohai_softwarei plugin'
version          '1.0.0'
depends          'ohai'
